name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Unit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GOPRIVATE: "github.com/ava-labs"
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-go-for-project
      - name: test-unit
        shell: bash
        run: make unit-test

  E2E:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GOPRIVATE: "github.com/ava-labs"
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-go-for-project
      - name: Start dependencies
        shell: bash
        run: docker compose up -d
      - name: Wait for services
        shell: bash
        run: sleep 10
      - name: Run e2e tests
        shell: bash
        run: make e2e-test
      - name: Stop dependencies
        if: always()
        shell: bash
        run: docker compose down

  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GOPRIVATE: "github.com/ava-labs"
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-go-for-project
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=10m
