name: PUBLISH LATEST DOCKER IMAGE
on:
  push:
    branches:
      - "main"
permissions:
  contents: read
jobs:
  BuildAndPush:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
        
      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: avaplatform/avalanche-indexer:latest
          platforms: linux/amd64

  BuildAndPushARM:
    name: Build and push Docker image to Docker Hub - ARM
    runs-on: ubuntu-24.04-arm-4-core
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
        
      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: avaplatform/avalanche-indexer:latest-arm64
          platforms: linux/arm64

  CombineLatestManifest:
    name: Combine manifests for latest (multi-arch)
    runs-on: ubuntu-latest
    needs: [BuildAndPush, BuildAndPushARM]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Create and push multi-arch latest manifest
        run: |
          docker buildx imagetools create \
            -t avaplatform/avalanche-indexer:latest \
            avaplatform/avalanche-indexer:latest \
            avaplatform/avalanche-indexer:latest-arm64
