name: RELEASE DOCKER IMAGE
on:
  push:
    tags:
      - '*'
permissions:
  contents: read
jobs:
  CreateAndPush:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          pull: true
          platforms: linux/amd64
          tags: |
            avaplatform/avalanche-indexer:${{ github.ref_name }}-amd64
  CreateAndPushARM:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-24.04-arm
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASS }}

        - name: Push to Docker Hub
          uses: docker/build-push-action@v6
          with:
            push: true
            pull: true
            platforms: linux/arm64
            tags: |
              avaplatform/avalanche-indexer:${{ github.ref_name }}-arm64
  CombineManifests:
      name: Combine manifests for multi-arch
      runs-on: ubuntu-latest
      needs: [CreateAndPush, CreateAndPushARM]
      steps:
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASS }}

        - name: Create and push multi-arch manifest
          run: |
            docker buildx imagetools create \
              -t avaplatform/avalanche-indexer:${{ github.ref_name }} \
              avaplatform/avalanche-indexer:${{ github.ref_name }}-amd64 \
              avaplatform/avalanche-indexer:${{ github.ref_name }}-arm64
